---
deployment:
 tasks:
 - export DEPLOYPATH=/home/digiwebcam/public_html/product
 - /bin/cp index.php $DEPLOYPATH
 - /bin/cp index.php $DEPLOYPATH
 - /bin/cp .cpanel.yml $DEPLOYPATH
 - /bin/cp -R * $DEPLOYPATH
 command: cp -r /home/digiwebcam/public_html/product
  with_items:
   - "index.html"
   - "static/"